coti-ethers
coti-io/coti-sdk-typescript pull request #20
Opened 2024-08-21 08:15 UTC by eitanz-coti

2024-08-22 08:46 UTC, smiller-coti commented on src/crypto_utils.ts
> -export function generateAesKey(): string {
I think we should just delete this function. It is not useful for anything other than one small part of the TS SDK examples. We can come up with a workaround

2024-08-22 08:47 UTC, smiller-coti requested changes
See comments

2024-09-24 20:41 UTC, gmesika-coti approved these changes

2024-09-26 19:23 UTC, gmesika-coti requested changes

2024-09-26 19:23 UTC, gmesika-coti commented on src/account/onboard.ts
> -  const receipt = await (await contract.onboardAccount(publicKey, signedEK, { gasLimit: 12000000 })).wait()
gas limit should be a var

2024-09-26 19:23 UTC, gmesika-coti commented on src/account/onboard.ts
> -  if (!receipt || !receipt.logs || !receipt.logs[0]) {
we should check if receipt.status is 1 or not

2024-09-26 19:23 UTC, gmesika-coti commented on src/account/onboard.ts
> -    const {publicKey, privateKey} = generateRSAKeyPair()
plz mention in var name it is the rsa

2024-10-06 20:02 UTC, gmesika-coti commented
version #0.6.5

2024-10-06 20:02 UTC, gmesika-coti commented
version #0.6.5

2024-10-06 20:02 UTC, closed without merging