alignments v1
coti-io/coti-sdk-typescript pull request #7
Opened 2024-07-04 07:41 UTC by eitanz-coti

alignments v1

2024-07-14 15:24 UTC, gmesika-coti requested changes

2024-07-14 15:24 UTC, gmesika-coti commented on src/account/confidential-account.ts
> +        console.log("eitan ConfidentialAccount")
?

2024-07-14 15:24 UTC, gmesika-coti commented on src/libs/libs_readme.md
> +# crypto_utils.ts
why to have only readme in the dir?

2024-07-14 15:24 UTC, gmesika-coti commented on README.md
> +All repositories specified below contain smart contracts that implement confidentiality features using the COTI V2
please make sure no changes of spaces or new lines for no reason

2024-07-14 15:24 UTC, gmesika-coti commented on README.md
> +|--------------------------------|------------|------------|-------------|----------------|------------------------------------------------------------------------------------------------------------
messed table

2024-07-14 15:24 UTC, gmesika-coti commented on src/utils.ts
> +import {ethers, JsonRpcProvider, Provider, toNumber, TransactionRequest, Wallet,} from "ethers";
this files should have being ethers-utils

2024-07-15 06:59 UTC, eitanz-coti commented on src/account/confidential-account.ts
> +        console.log("eitan ConfidentialAccount")
removed.

2024-07-15 07:02 UTC, eitanz-coti commented on src/utils.ts
> +import {ethers, JsonRpcProvider, Provider, toNumber, TransactionRequest, Wallet,} from "ethers";
renamed

2024-07-15 07:06 UTC, eitanz-coti commented on README.md
> +All repositories specified below contain smart contracts that implement confidentiality features using the COTI V2
no changes appears in github.

2024-08-07 06:28 UTC, eitanz-coti commented
merged already.

2024-08-07 06:28 UTC, closed without merging